USE KIEMTRALTM
GO
ALTER PROC SP_INS_BANGDIEM (
	@MASV CHAR(8),
	@LAN SMALLINT,
	@NGAYTHI VARCHAR(103),
	@DIEM FLOAT,
	@BAITHI NTEXT
) AS
BEGIN
	INSERT INTO BANGDIEM(MASV,LAN,NGAYTHI,DIEM,BAITHI)
	VALUES(@MASV,@LAN,CONVERT(DATETIME,@NGAYTHI,103),@DIEM,@BAITHI)
END

--EXEC SP_INS_BANGDIEM '007','2','23/10/2020','8','THU 2'