USE [KIEMTRALTM]
GO
CREATE PROC [dbo].[SP_UPD_BANGDIEM] (
	@MASV CHAR(8),
	@LAN SMALLINT,
	@NGAYTHI VARCHAR(103),
	@DIEM FLOAT,
	@BAITHI NTEXT
) AS
BEGIN
	UPDATE BANGDIEM
	SET LAN = @LAN,NGAYTHI = CONVERT(DATETIME,@NGAYTHI,103),DIEM = @DIEM,BAITHI = @BAITHI
	WHERE MASV = @MASV
END